### ISSUE TITLE
Change Readme File

### ISSUE THREAD

**Issue by shubhamchhabra** [judygab/nextjs-portfolio#14]
Your Repo Link is incorrect : https://github.com/judygab/nextjs-portfolio.git

**Comment by Dev-Sambhav** [comment]
Hey @judygab, i spotted a small issue in the README.md – the repo link was wrong. Fixed it in my latest PR, It's just a tiny tweak, tested it, everything's cool. Can you check it out and merge when you can?

**Comment by judygab** [comment]
@shubhamchhabra thanks for pointing it out and @Dev-Sambhav merged it, thank you for the contribution!
